version: 0.2

# Buildspec to generate test data before running E2E in parallel. It is important that all test data is independent of each other.

batch:
  fast-fail: false
  build-list:
    - identifier: cypress-e2e-testdata
      env:
        variables:
          image: public.ecr.aws/cypress-io/cypress/browsers:node14.17.0-chrome88-ff89

phases:
  install:
    runtime-versions:
      python: 3.x
  pre_build:
    commands:
      - ls ~/.aws
      - aws configure get aws_access_key_id
      - export ACCESS_KEY_ID=$(aws configure get aws_access_key_id)
      - echo $ACCESS_KEY_ID
      - aws sts assume-role --role-arn $ROLE_ARN --role-session-name test > Credentials
      - export CYPRESS_AWS_ACCESS_KEY_ID=$(cat Credentials | jq -r '.Credentials.AccessKeyId')
      - export CYPRESS_AWS_SECRET_ACCESS_KEY=$(cat Credentials | jq -r '.Credentials.SecretAccessKey')
      - export CYPRESS_AWS_SESSION_TOKEN=$(cat Credentials | jq -r '.Credentials.SessionToken')
      - export CYPRESS_AWS_REGION=${AWS_REGION}
  build:
    commands:
      - cd test_data
      - python create_test_data.py
