version: 0.2

# Buildspec to generate a test report after all E2E tests are finished running.


phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - npm install
      - aws sts assume-role --role-arn $ROLE_ARN --role-session-name test > Credentials
      - export CYPRESS_AWS_ACCESS_KEY_ID=$(cat Credentials | jq -r '.Credentials.AccessKeyId')
      - export CYPRESS_AWS_SECRET_ACCESS_KEY=$(cat Credentials | jq -r '.Credentials.SecretAccessKey')
      - export CYPRESS_AWS_SESSION_TOKEN=$(cat Credentials | jq -r '.Credentials.SessionToken')
      - export CYPRESS_AWS_REGION=${AWS_REGION}
  build:
    commands:
      - if [ -d "messages" ]; then ls -l messages; fi
      - if [ -d "messages" ]; then if [ -a messages/* ]; then  rm messages/*; fi; fi
      - if [ ! -d "messages" ]; then mkdir messages; fi
      - aws s3 cp s3://$TESTREPORTS_BUCKET/messages messages --recursive
      - if [ ! -d "TestReport" ]; then mkdir TestReport; fi
      - npx cucumber-merge-messages messages/*.ndjson > cucumber-messages.ndjson
      - npm run create:cucumber:report
      - if [ -d "cypress/screenshots" ]; then aws s3 cp cypress/screenshots s3://$S3_BUCKET/cypress/$CODEBUILD_BUILD_NUMBER/screenshots --recursive; fi
      - if [ -d "cypress/videos" ]; then aws s3 cp cypress/videos s3://$TESTREPORTS_BUCKET/videos --recursive; fi
      - if [ -d "TestReport" ]; then aws s3 cp TestReport s3://$TESTREPORTS_BUCKET/TestReport --recursive; aws s3 cp TestReport s3://$TESTREPORTS_BUCKET --recursive; fi
  post_build:
    commands:
      - aws s3 rm s3://$TESTREPORTS_BUCKET/messages --recursive
artifacts:
  files:
    - '**/*'
