version: 0.2

# Buildspec to generate test data before running E2E in parallel. It is important that all test data is independent of each other.

phases:
  install:
    runtime-versions:
      python: 3.x
  build:
    commands:
      - cd test_data
      - pip install babel
      - pip install requests
      - python create_test_data.py
