version: 0.2

# Buildspec to generate test data before running E2E in parallel. It is important that all test data is independent of each other.

batch:
  fast-fail: true

phases:
  install:
    runtime-versions:
      python: 3.x
  pre_build:
    commands:
      - export env=test
      - export ROLE_ARM=arn:aws:iam::282305091481:role/service-role/codebuild-warmup-service-role
      - aws sts assume-role --role-arn $ROLE_ARN --role-session-name test > Credentials
      - export CYPRESS_AWS_ACCESS_KEY_ID=$(cat Credentials | jq -r '.Credentials.AccessKeyId')
      - export CYPRESS_AWS_SECRET_ACCESS_KEY=$(cat Credentials | jq -r '.Credentials.SecretAccessKey')
      - export CYPRESS_AWS_SESSION_TOKEN=$(cat Credentials | jq -r '.Credentials.SessionToken')
      - export CYPRESS_AWS_REGION='eu-west-1'
      # Remove search indices from previous test runs
  build:
    commands:
      # Get token
      - cd test_data
      - TOKEN=$(python login_warmup.py)
      - echo $TOKEN
      - echo $env

      # POST publication
      - curl -i -X POST https://api.{$env}.nva.aws.unit.no/publication -H "Content-Type:application/json" -H "Authorization:Bearer {$TOKEN}" -d '{"type":"NonExistingType"}'

      # PUT publication
      - curl -i -X PUT https://api.{$env}.nva.aws.unit.no/publication/0184be6e2eeb-dc2a295d-dfb0-4f0d-b0ec-5bea756356b3 -H "Content-Type:application/json" -H "Authorization:Bearer {TOKEN}" -d '{"type":"NonExistingType"}'

      # GET publication
      - curl -i -X GET https://api.{$env}.nva.aws.unit.no/publication/0184be6e2eeb-dc2a295d-dfb0-4f0d-b0ec-5bea756356b3 -H "Accept:application/json"

      # GET organization
      - curl -i -X GET https://api.{$env}.nva.aws.unit.no/cristin/organization/20754.0.0.0 -H "Accept:application/json"

      # GET person
      - curl -i -X GET https://api.{$env}.nva.aws.unit.no/cristin/person/1136806 -H "Accept:application/json"

      # GET search person
      - curl -i -X GET https://api.{$env}.nva.aws.unit.no/cristin/person?name=test -H "Accept:application/json"

      # GET search publication
      - curl -i -X GET https://api.{$env}.nva.aws.unit.no/search/resources -H "Accept:application/json"

      # GET search tickets
      - curl -i -X GET https://api.{$env}.nva.aws.unit.no/search/tickets -H "Accept:application/json" -H "Authorization:Bearer {$TOKEN}"
