version: 0.2

# Buildspec to generate test data before running E2E in parallel. It is important that all test data is independent of each other.

phases:
  install:
    runtime-versions:
      python: 3.x
  pre_build:
    commands:
      - pip install uv
  build:
    commands:
      - cd test_data
      - uv run --frozen create_test_data.py
