version: 0.2

# Buildspec to generate test data before running E2E in parallel. It is important that all test data is independent of each other.

batch:
  fast-fail: true

phases:
  install:
    runtime-versions:
      python: 3.x
  pre_build:
    commands:
      - export env=test
      - export ROLE_ARM=arn:aws:iam::282305091481:role/service-role/codebuild-warmup-service-role
      - aws sts assume-role --role-arn $ROLE_ARN --role-session-name test > Credentials
      - export CYPRESS_AWS_ACCESS_KEY_ID=$(cat Credentials | jq -r '.Credentials.AccessKeyId')
      - export CYPRESS_AWS_SECRET_ACCESS_KEY=$(cat Credentials | jq -r '.Credentials.SecretAccessKey')
      - export CYPRESS_AWS_SESSION_TOKEN=$(cat Credentials | jq -r '.Credentials.SessionToken')
      - export CYPRESS_AWS_REGION='eu-west-1'
      # Remove search indices from previous test runs
  build:
    commands:
      # Get token
      - cd test_data
      - TOKEN=$(python login_warmup.py)
      - echo $TOKEN
      - echo $env

      # POST publication
      - curl -S -s -o /dev/null -i -X POST https://api.{$env}.nva.aws.unit.no/publication -H "Content-Type:application/json" -H "Authorization:Bearer {$TOKEN}" -d '{"type":"NonExistingType"}'

      # PUT publication
      - curl -S -s -o /dev/null -i -X PUT https://api.{$env}.nva.aws.unit.no/publication/0184be6e2eeb-dc2a295d-dfb0-4f0d-b0ec-5bea756356b3 -H "Content-Type:application/json" -H "Authorization:Bearer {TOKEN}" -d '{"type":"NonExistingType"}'

      # GET publication
      - curl -S -s -o /dev/null -i -X GET https://api.{$env}.nva.aws.unit.no/publication/0184be6e2eeb-dc2a295d-dfb0-4f0d-b0ec-5bea756356b3 -H "Accept:application/json"

      # GET publication by-owner
      - curl -i -X GET https://api.{$env}.nva.aws.unit.no/publication/by-owner -H "Content-Type:application/json" -H "Authorization:Bearer {$TOKEN}"

      # GET organization
      - curl -S -s -o /dev/null -i -X GET https://api.{$env}.nva.aws.unit.no/cristin/organization/20754.0.0.0 -H "Accept:application/json"

      # GET organization persons
      - curl -S -s -o /dev/null -i -X GET https://api.{$env}.nva.aws.unit.no/cristin/organization/20754.0.0.0/persons -H "Accept:application/json"

      # GET customer
      - curl -S -s -o /dev/null  -i -X GET https://api.{$env}.nva.aws.unit.no/customer -H "Content-Type:application/json" -H "Authorization:Bearer {$TOKEN}"

      # GET institution users
      - curl -S -s -o /dev/null  -i -X GET https://api.{$env}.nva.aws.unit.no/users-roles/institutions/users?institution=https%3A%2F%2Fapi.dev.nva.aws.unit.no%2Fcristin%2Forganization%2F20754 -H "Content-Type:application/json" -H "Authorization:Bearer {$TOKEN}"

      # GET customer vocabularies
      - curl -S -s -o /dev/null  -i -X GET https://api.{$env}.nva.aws.unit.no/customer/0baf8fcb-b18d-4c09-88bb-956b4f659103/vocabularies -H "Content-Type:application/json" -H "Authorization:Bearer {$TOKEN}"

      # GET person
      - curl -S -s -o /dev/null -i -X GET https://api.{$env}.nva.aws.unit.no/cristin/person/1136806 -H "Accept:application/json"

      # GET search person
      - curl -S -s -o /dev/null -i -X GET https://api.{$env}.nva.aws.unit.no/cristin/person?name=test -H "Accept:application/json"

      # GET search publication
      - curl -S -s -o /dev/null -i -X GET https://api.{$env}.nva.aws.unit.no/search/resources -H "Accept:application/json"

      # GET search tickets
      - curl -S -s -o /dev/null -i -X GET https://api.{$env}.nva.aws.unit.no/search/tickets -H "Accept:application/json" -H "Authorization:Bearer {$TOKEN}"

      # GET project list
      - curl -S -s -o /dev/null -i -X GET https://api.{$env}.nva.aws.unit.no/cristin/project -H "Accept:application/json"

      # POST project
      - curl -S -s -o /dev/null -i -X POST https://api.{$env}.nva.aws.unit.no/cristin/project -H "Content-Type::application/json" -H "Authorization:Bearer {$TOKEN}" -d '{}'

