version: 0.2

# Buildspec to run E2E tests in parallel. To add more builds to the parallel run,
# add runners to the list of runners in the format:
#
# - identifier: runner<id>
#   buildspec:
#     - template/buildspec.testrun.yml
#   env:
#     variables:
#       RUNNER: <id>
#   ignore-failure: true
#
# Add new runners to the depend-on for the test report step

batch:
  build-graph:
    - identifier: runner1
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 1
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: runner2
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 2
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: runner3
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 3
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: runner4
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 4
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: runner5
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 5
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: runner6
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 6
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: runner7
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 7
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: runner8
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 8
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: runner9
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 9
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: runner10
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 10
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: runner11
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 11
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: runner12
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 12
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: runner13
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 13
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: runner14
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 14
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: runner15
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 15
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: runner16
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 16
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: runner17
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 17
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: runner18
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 18
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: runner19
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 19
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: runner20
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 20
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: runner21
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 21
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: runner22
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 22
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: runner23
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 23
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: runner24
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 24
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: runner25
      buildspec: template/buildspec.testrun.yml
      env:
        variables:
          RUNNER: 25
          image: public.ecr.aws/cypress-io/cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1
      ignore-failure: true
    - identifier: test_report
      buildspec: template/buildspec.testreport.yml
      depend-on:
        - runner1
        - runner2
        - runner3
        - runner4
        - runner5
        - runner6
        - runner7
        - runner8
        - runner9
        - runner10
        - runner11
        - runner12
        - runner13
        - runner14
        - runner15
        - runner16
        - runner17
        - runner18
        - runner19
        - runner20
        - runner21
        - runner22
        - runner23
        - runner24
        - runner25
