AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Deploy and run Cypress end-to-end tests

Resources:
  TestDataStack:
    Type: AWS::CloudFormation::Stack
        Properties:
        TemplateURL: !Sub <template to create testdata stack>
        TimeoutInMinutes: 60
  CypressStack:
    Type: AWS::CloudFormation::Stack
        Properties:
        TemplateURL: !Sub <template to create Cypress deploy and run stack>
        TimeoutInMinutes: 60
