version: 0.2

env:
  parameter-store:
    CYPRESS_baseUrl: CognitoFrontendApplicationUrl
    CYPRESS_AWS_IDENTITY_POOL_ID: CognitoIdentityPoolId
    CYPRESS_AWS_USER_POOL_ID: CognitoUserPoolId
    CYPRESS_AWS_CLIENT_ID: CognitoUserPoolAppClientId
    CYPRESS_REACT_APP_URL: /NVA/ApplicationDomain
    CYPRESS_REACT_APP_API_HOST: /NVA/ApiDomain

batch:
  fast-fail: false
  build-list:
    - identifier: cypress-e2e-tests
      env:
        variables:
          image: public.ecr.aws/cypress-io/cypress/browsers:node14.17.0-chrome88-ff89

phases:
  install:
    runtime-versions:
      nodejs: 14
      python: 3.x
  pre_build:
    commands:
      - wget https://github.com/BIBSYSDEV/NVA-end-to-end-testing/archive/refs/heads/test-deploy.zip
      - unzip test-deploy.zip
      - cd NVA-end-to-end-testing-test-deploy
      - npm install
      - aws sts assume-role --role-arn $ROLE_ARN --role-session-name test > Credentials
      - export CYPRESS_AWS_ACCESS_KEY_ID=$(cat Credentials | jq -r '.Credentials.AccessKeyId')
      - export CYPRESS_AWS_SECRET_ACCESS_KEY=$(cat Credentials | jq -r '.Credentials.SecretAccessKey')
      - export CYPRESS_AWS_SESSION_TOKEN=$(cat Credentials | jq -r '.Credentials.SessionToken')
      - export CYPRESS_AWS_REGION=${AWS_REGION}
  build:
    commands:
      - cd test_data
      - python create_test_data.py
      - cd ..
      - npx cypress run --browser chrome
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - NVA-end-to-end-testing-test-deploy/node_modules/**/*
