version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "install cypress dependencies..."
      - apt-get update
      - apt-get install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb jq
      - npm install --save-dev cypress-cucumber-preprocessor
      - npm install uuid
      - npm install aws-sdk
      - npm install aws-amplify
      - npm install
      - TEMP_ROLE=`aws sts assume-role --role-arn $ROLE_ARN --role-session-name test`
      - export TEMP_ROLE
      - export CYPRESS_AWS_ACCESS_KEY_ID=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.AccessKeyId')
      - export CYPRESS_AWS_SECRET_ACCESS_KEY=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SecretAccessKey')
      - export CYPRESS_AWS_SESSION_TOKEN=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SessionToken')
  pre_build:
    commands:
      - export CYPRESS_baseUrl=$CYPRESS_REACT_APP_URL
      - echo $CYPRESS_baseUrl
  build:
    commands:
      - npx cypress run
  post_build:
    commands:
      - echo "post_build step"
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - node_modules/**/*
