version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "install cypress dependencies..."
      - apt-get update
      - apt-get install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb jq
      - npm install --save-dev cypress-cucumber-preprocessor
      - npm install uuid
      - npm install aws-sdk
      - npm install aws-amplify
      - npm install
      - echo '-------------------------'
      - ls -l ~/.aws
      - echo '-------------------------'
  pre_build:
    commands:
      - export CYPRESS_baseUrl=$CYPRESS_REACT_APP_URL
      - echo $CYPRESS_baseUrl
  build:
    commands:
      - npx cypress run
  post_build:
    commands:
      - echo "post_build step"
artifacts:
  files:
    - '**/*'
    - package.json
cache:
  paths:
    - node_modules/**/*
