import { dataTestId } from './dataTestIds';

export const registrationFields = {
  'description': {
    'tab': dataTestId.registrationWizard.stepper.descriptionStepButton,
    'title': {
      type: 'text',
      fieldTestId: dataTestId.registrationWizard.description.titleField,
      elementType: 'input',
      landingPageTestId: dataTestId.registrationLandingPage.title,
      value: 'Test registration title',
    },
    'abstract': {
      type: 'text',
      fieldTestId: dataTestId.registrationWizard.description.abstractField,
      elementType: 'textArea',
      landingPageTestId: dataTestId.registrationLandingPage.abstractAccordion,
      value: 'Test registration abstract',
    },
    'description': {
      type: 'text',
      fieldTestId: dataTestId.registrationWizard.description.descriptionField,
      elementType: 'textArea',
      landingPageTestId: '',
      value: 'Test registration description',
    },
    'keywords': {
      type: 'text',
      fieldTestId: dataTestId.registrationWizard.description.tagField,
      elementType: 'chip',
      landingPageTestId: dataTestId.registrationLandingPage.keywords,
      value: 'Test registration keyword',
    },
    'vocabularies': {
      type: 'search',
      fieldTestId: dataTestId.registrationWizard.description.vocabularyRow('hrcsActivity'),
      elementType: 'chip',
      landingPageTestId: dataTestId.registrationLandingPage.vocabularies,
      value: 'Underpinning Research',
    },
    'date': {
      type: 'date',
      fieldTestId: dataTestId.registrationWizard.description.datePublishedField,
      value: '11.11.2021',
      elementType: 'input',
      landingPageTestId: '',
    },
    'language': {
      type: 'select',
      fieldTestId: dataTestId.registrationWizard.description.languageField,
      elementType: 'search',
      landingPageTestId: dataTestId.registrationLandingPage.primaryLanguage,
      value: 'Spanish',
    },
    'project': {
      type: 'search',
      fieldTestId: dataTestId.registrationWizard.description.projectSearchField,
      elementType: 'search',
      landingPageTestId: dataTestId.registrationLandingPage.projectsAccordion,
      value: 'Testprosjekt NVA',
    },
  },
  'files and license': {
    'tab': dataTestId.registrationWizard.stepper.filesStepButton,
    'file': {
      type: 'file',
      fieldTestId: dataTestId.registrationWizard.files.filesAccordion,
      elementType: 'file',
      landingPageTestId: dataTestId.registrationLandingPage.filesAccordion,
      value: 'example.json',
    },
    'version': {
      type: 'checkbox',
      fieldTestId: dataTestId.registrationWizard.files.version,
      elementType: 'radio',
      landingPageTestId: dataTestId.registrationLandingPage.version,
      value: 'Accepted',
      checkbox: {
        selected: 'first',
      },
    },
    'author agreement': {
      type: 'checkbox',
      fieldTestId: dataTestId.registrationWizard.files.administrativeAgreement,
      elementType: 'checkbox',
      landingPageTestId: dataTestId.registrationLandingPage.administrativeAgreement,
      value: false,
      checkbox: {
        selected: 'check',
      },
    },
    'date': {
      type: 'date',
      fieldTestId: dataTestId.registrationWizard.files.embargoDateField,
      elementType: 'input',
      landingPageTestId: '',
      value: '11.11.2021',
    },
    'terms of use': {
      type: 'select',
      fieldTestId: dataTestId.registrationWizard.files.selectLicenseField,
      elementType: 'search',
      landingPageTestId: dataTestId.registrationLandingPage.license,
      value: 'CC BY',
    },
  },
};

export const contributorsCommon = {
  'author': {
    type: 'add',
    fieldTestId: dataTestId.registrationWizard.contributors.addContributorButton,
    landingPageTestId: dataTestId.registrationLandingPage.authorLink(''),
    value: 'Withauthor TestUser',
    add: {
      searchFieldTestId: 'search-field',
      searchValue: 'TestUser',
      resultsTestId: dataTestId.registrationWizard.contributors.authorRadioButton,
      selectButtonTestId: dataTestId.registrationWizard.contributors.selectUserButton,
    },
  },
  'contributors': {
    type: 'add',
    fieldTestId: dataTestId.registrationWizard.contributors.addContributorButton,
    landingPageTestId: dataTestId.registrationLandingPage.contributors,
    value: 'Withauthor TestUser',
    add: {
      select: {
        selectTestId: 'select-contributor-type',
        value: 'Other',
      },
      searchFieldTestId: 'search-field',
      searchValue: 'TestUser',
      resultsTestId: dataTestId.registrationWizard.contributors.authorRadioButton,
      selectButtonTestId: dataTestId.registrationWizard.contributors.selectUserButton,
    },
  },
};

export const resourceTypeFields = {
  publisher: {
    type: 'search',
    fieldTestId: dataTestId.registrationWizard.resourceType.publisherField,
    elementType: 'search',
    landingPageTestId: '',
    value: 'Det Kongelige Norske Videnskabers Selskab',
  },
  scientificField: {
    type: 'search',
    fieldTestId: dataTestId.registrationWizard.resourceType.scientificSubjectField,
    elementType: 'search',
    landingPageTestId: dataTestId.registrationLandingPage.npi,
    value: 'Computer engineering',
  },
  isbn: {
    type: 'text',
    fieldTestId: dataTestId.registrationWizard.resourceType.isbnField,
    elementType: 'input',
    landingPageTestId: '',
    value: '9781234567897',
    landingPageValue: '978-12-345-6789-7',
  },
  pages: {
    type: 'text',
    fieldTestId: dataTestId.registrationWizard.resourceType.pagesField,
    elementType: 'input',
    landingPageTestId: '',
    value: '123',
  },
  seriesTitle: {
    type: 'search',
    fieldTestId: dataTestId.registrationWizard.resourceType.seriesField,
    elementType: 'search',
    landingPageTestId: '',
    value: 'ACS Central Science',
  },
  seriesNumber: {
    type: 'text',
    fieldTestId: dataTestId.registrationWizard.resourceType.seriesNumber,
    elementType: 'input',
    landingPageTestId: '',
    value: '123',
  },
  bookContent: {
    type: 'select',
    fieldTestId: dataTestId.registrationWizard.resourceType.contentField,
    elementType: 'search',
    landingPageTestId: '',
    value: 'Academic monograph',
  },
  journalContent: {
    type: 'select',
    fieldTestId: dataTestId.registrationWizard.resourceType.contentField,
    elementType: 'search',
    landingPageTestId: '',
    value: 'Academic article',
  },
  chapterContent: {
    type: 'select',
    fieldTestId: dataTestId.registrationWizard.resourceType.contentField,
    elementType: 'search',
    landingPageTestId: '',
    value: 'Academic chapter',
  },
  journal: {
    type: 'search',
    fieldTestId: dataTestId.registrationWizard.resourceType.journalField,
    elementType: 'search',
    landingPageTestId: '',
    value: 'Academic Research International',
  },
  articleTitle: {
    type: 'search',
    fieldTestId: dataTestId.registrationWizard.resourceType.corrigendumForField,
    elementType: 'search',
    landingPageTestId: '',
    value: 'Test article corrigendum',
  },
  volume: {
    type: 'text',
    fieldTestId: dataTestId.registrationWizard.resourceType.volumeField,
    elementType: 'input',
    landingPageTestId: '',
    value: '111',
  },
  issue: {
    type: 'text',
    fieldTestId: dataTestId.registrationWizard.resourceType.issueField,
    elementType: 'input',
    landingPageTestId: '',
    value: '222',
  },
  pagesFrom: {
    type: 'text',
    fieldTestId: dataTestId.registrationWizard.resourceType.pagesFromField,
    elementType: 'input',
    landingPageTestId: '',
    value: '333',
  },
  pagesTo: {
    type: 'text',
    fieldTestId: dataTestId.registrationWizard.resourceType.pagesToField,
    elementType: 'input',
    landingPageTestId: '',
    value: '444',
  },
  articleNumber: {
    type: 'text',
    fieldTestId: dataTestId.registrationWizard.resourceType.articleNumberField,
    elementType: 'input',
    landingPageTestId: '',
    value: '555',
  },
  peerReview: {
    type: 'checkbox',
    fieldTestId: dataTestId.registrationWizard.resourceType.peerReviewed,
    elementType: 'radio',
    landingPageTestId: '',
    value: 'Yes',
    checkbox: {
      selected: 'first',
    },
  },
  partOf: {
    type: 'search',
    fieldTestId: dataTestId.registrationWizard.resourceType.partOfField,
    elementType: 'search',
    landingPageTestId: '',
    value: 'Antologi',
  },
  titleOfEvent: {
    type: 'text',
    fieldTestId: dataTestId.registrationWizard.resourceType.eventTitleField,
    elementType: 'input',
    landingPageTestId: '',
    value: 'Test event title',
  },
  eventOrganizer: {
    type: 'text',
    fieldTestId: dataTestId.registrationWizard.resourceType.eventOrganizerField,
    elementType: 'input',
    landingPageTestId: '',
    value: 'Test event organizer',
  },
  eventPlace: {
    type: 'text',
    fieldTestId: dataTestId.registrationWizard.resourceType.eventPlaceField,
    elementType: 'input',
    landingPageTestId: '',
    value: 'Test event place',
  },
  eventCountry: {
    type: 'select',
    fieldTestId: dataTestId.registrationWizard.resourceType.eventCountryField,
    elementType: 'input',
    landingPageTestId: '',
    value: 'American Samoa',
  },
  eventDateFrom: {
    type: 'date',
    fieldTestId: dataTestId.registrationWizard.resourceType.dateFromField,
    elementType: 'input',
    landingPageTestId: '',
    value: '11.11.2021',
  },
  eventDateTo: {
    type: 'date',
    fieldTestId: dataTestId.registrationWizard.resourceType.dateToField,
    elementType: 'input',
    landingPageTestId: '',
    value: '11.11.2021',
  },
  artisticType: {
    type: 'select',
    fieldTestId: dataTestId.registrationWizard.resourceType.artisticTypeField,
    elementType: 'input',
    landingPageTestId: '',
    value: 'Product design',
    landingPageValue: 'ProductDesign',
  },
  artisticDescription: {
    type: 'text',
    fieldTestId: dataTestId.registrationWizard.resourceType.artisticDescriptionField,
    elementType: 'textArea',
    landingPageTestId: '',
    value: 'Test artistic description',
  },
  exhibitionPlace: {
    type: 'add',
    fieldTestId: dataTestId.registrationWizard.resourceType.addVenueButton,
    elementType: 'place',
    landingPageTestId: '',
    value: 'Test exhibition place',
    add: {
      fields: {
        [dataTestId.registrationWizard.resourceType.venueNameField]: 'Test exhibition place',
        [dataTestId.registrationWizard.resourceType.dateFromField]: '11.11.2021',
        [dataTestId.registrationWizard.resourceType.dateToField]: '11.11.2021',
      },
      selectButtonTestId: dataTestId.registrationWizard.resourceType.saveVenueButton,
    },
  },
};

